<p class="lien"><a href="index.php?controller=home&action=index" title="retour à l'accueil"><i class="fa fa-home"></i> Accueil </a><a href="index.php?controller=homeadmin&action=index" title="accueil admin">Administration /</a> Liste des administrateurs </p>
<h2><img src="assets/img/logo/signeG.svg" alt="signeG"><span> GESTION DES ADMINISTRATEURS<img src="assets/img/logo/signeD.svg" alt="signeD"></span></h2>
<div class="list_product">
  <?php include 'aside_bar.phtml' ?>
  <div class=table-list>
    <h3>LISTES DES ADMINISTRATEURS</h3>
    <table class="generic-table listproduct">
      <thead>
        <tr>
          <th>ID</th>
          <th>Nom</th>
          <th>Prénom</th>
          <th>Email</th>
          <th><a class="btn" href="index.php?controller=useradmin&action=insert" title="insertion d'un nouvel administarteur"><i class="fas fa-plus"></i></a></th>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($users as $user) : ?>
          <tr>
            <td><?= htmlspecialchars($user['id']) ?></td>
            <td><?= htmlspecialchars($user['lastName']) ?></td>
            <td><?= htmlspecialchars($user['firstName']) ?></td>
            <td><?= htmlspecialchars($user['email'])?></td>
            <td class="icone_e"><a href="index.php?controller=useradmin&action=delete&id=<?= intval($user['id']); ?>" title="supprimer un administrateur" class="supprimer"><i class="fa fa-trash" aria-hidden="true"></i></a></td>
          </tr>
        <?php endforeach; ?>
      </tbody>
      <tfoot>
        <tr>
        <td colspan="5">
          <strong>($NB d'administrateur au total : <?= htmlspecialchars(count($users)) ?>)</strong>
        </td>
        </tr>
      </tfoot>
    </table>
  </div>
</div>
<script src="assets/js/ajax.js"></script>