<aside class="sidebar bar-select">
  <nav>
    <h3> Commande à la carte </h3>
    <ul>
      <li><a href="index.php?controller=homeadmin&action=index" title="gestion des produit">Gestion des produits</a></li>
      <li><a href="index.php?controller=milkadmin&action=index" title="gestion des laits">Gestion des lait</a></li>
      <li><a href="index.php?controller=doughadmin&action=index" title="gestion des pâtes">Gestion des pâtes</a></li>
      <li><a href="index.php?controller=regionadmin&action=index" title="gestion des régions">Gestion des regions</a></li>
      <li><a href="index.php?controller=wineadmin&action=index" title="gestion des vins">Gestion des vins</a></li>
      <li><a href="index.php?controller=shapeadmin&action=index" title="gestion des formes">Gestion des formes</a></li>
      <li><a href="index.php?controller=knifeadmin&action=index" title="gestion des couteaux">Gestion des couteaux</a></li>
      <li><a href="index.php?controller=trayadmin&action=index" title="gestion des plateaux">Gestion des plateaux</a></li>
      <li><a href="index.php?controller=weightadmin&action=index" title="gestion des poids">Gestion des poids</a></li>
      <li><a href="index.php?controller=shippingadmin&action=index" title="gestion des frais de port">Gestion des frais de port</a></li>
    </ul>
    <h3>Blog</h3>
    <ul>
      <li><a href="index.php?controller=postadmin&action=index" title="gestion des articles">Gestion des articles</a></li>
      <li><a href="index.php?controller=categoryadmin&action=index" title="gestion des catégories">Gestion des catégories</a></li>
    </ul>
    <h3>Utilisateurs</h3>
    <ul>
      <li><a href="index.php?controller=useradmin&action=index" title="gestion des administrateur">Gestion des Administrateurs</a></li>
      <li><a href="index.php?controller=useradmin&action=AllUser" title="gestion des utilisateurs">Gestion des Utilisateurs</a></li>
    </ul>
    <h3>Commandes</h3>
    <ul>
      <li><a href="index.php?controller=orderadmin&action=index" title="gestion des commandes">Gestion des Commandes</a></li>
    </ul>
    <h3>Messages</h3>
    <ul>
      <li><a href="index.php?controller=messageadmin&action=index" title="gestion des messages">Gestion des Messages</a></li>
    </ul>
  </nav>
</aside>