<p class="lien"><a href="index.php?controller=home&action=index" title="retour à l'accueil"><i class="fa fa-home"></i> Accueil /</a><a href="index.php?controller=homeadmin&action=index" title="accueil admin">Administration /</a>Liste des categories </p>
<h2><img src="assets/img/logo/signeG.svg" alt="signeG"><span> GESTION DES CATEGORIES <img src="assets/img/logo/signeD.svg" alt="signeD"></span></h2>
<div class="list_product">
  <?php include 'aside_bar.phtml' ?>
  <div class=table-list>
    <?php if ($flash->hasMessages() == true) : ?>
      <div class="flash">
        <?php foreach ($flash->fetchMessages() as $message) : ?>
          <p><?= htmlspecialchars($message) ?></p>
        <?php endforeach ?>
      </div>
    <?php endif; ?>
    <h3>LISTES DES CATEGORIES</h3>
    <table class="generic-table listproduct">
      <thead>
        <tr>
          <th>Id</th>
          <th>Nom de la categorie</th>
          <th colspan=1><a class="btn" href="index.php?controller=categoryadmin&action=insert" title="insertion d'une nouvelle categorie"><i class="fas fa-plus"></i></a> </th>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($categorys as $category) : ?>
          <tr>
            <td><?= htmlspecialchars($category['id']) ?></td>
            <td><?= htmlspecialchars($category['name']) ?></td>
            <td class="icone_e"><a href="index.php?controller=categoryadmin&action=edit&id=<?= intval($category['id']); ?>" title="modifier une catégorie"><i class="fas fa-pen-nib"></i></a></td>
          </tr>
        <?php endforeach; ?>
      </tbody>
      <tfoot>
        <tr>
          <td colspan="3"><strong>($NB de categorie au total : <?= htmlspecialchars(count($categorys)) ?>)</strong></td>
        </tr>
      </tfoot>
    </table>
  </div>
</div>