<p class="lien"><a href="index.php?controller=home&action=index" title="retour à l'accueil"><i class="fa fa-home"></i> Accueil /</a><a href="index.php?controller=homeadmin&action=index" title="accueil admin">Administration /</a> Créer une pâte</p>
<h2><img src="assets/img/logo/signeG.svg" alt="signeG"><span> GESTION DES PATES<img src="assets/img/logo/signeD.svg" alt="signeD"></span></h2>
<div class="list_product">
  <?php include 'aside_bar.phtml' ?>
  <div class=table-list>
    <a class="btn" href="index.php?controller=doughadmin&action=insert" title="insertion d'une nouvelle pate"><i class="fas fa-plus"></i> Créer une pâte</a>
    <?php if ($flash->hasMessages() == true) : ?>
      <aside class="flash">
        <?php foreach ($flash->fetchMessages() as $message) : ?>
          <p><?= htmlspecialchars($message) ?></p>
        <?php endforeach ?>
      </aside>
    <?php endif; ?>
    <form method="POST" class="generic-form edit-form">
      <fieldset>
        <legend> <i class="fas fa-pen-nib"></i> Modifier le type de Pâtes</legend>
        <ul>
          <li>
            <label for="Name_dough">Type de Pâte</label>
            <input type="text" name="Name_dough" id="Name_dough" placeholder="Type de pâte">
          </li>
        </ul>
        <button class="btn" type="submit">ENREGISTRER</button>
        <a class="btn" href="index.php?controller=doughadmin&action=index" title="retour à la liste des pates">RETOUR</a>
      </fieldset>
    </form>
  </div>
</div>