<p class="lien"><a href="index.php?controller=home&action=index" title="retour à l'accueil"><i class="fa fa-home"></i> Accueil /</a> /<a href="index.php?controller=homeadmin&action=index" title="accueil admin">Administration /</a> Liste des pâtes </p>
<h2><img src="assets/img/logo/signeG.svg" alt="signeG"><span>GESTION DES PATES<img src="assets/img/logo/signeD.svg" alt="signeD"></span></h2>
<div class="list_product">
  <?php include 'aside_bar.phtml' ?>
  <div class=table-list>
    <?php if ($flash->hasMessages() == true) : ?>
      <aside class="flash">
        <?php foreach ($flash->fetchMessages() as $message) : ?>
          <p><?= htmlspecialchars($message) ?></p>
        <?php endforeach ?>
      </aside>
    <?php endif; ?>
    <h3>LISTES DES PATES</h3>
    <table class="generic-table listproduct">
      <thead>
        <tr>
          <th>ID</th>
          <th>Types de pâtes</th>
          <th colspan=1><a class="btn" href="index.php?controller=doughadmin&action=insert" title="insertion d'une nouvelle pâte"><i class="fas fa-plus"></i></a> </th>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($doughs as $dough) : ?>
          <tr>
            <td><?= htmlspecialchars($dough['id']) ?></td>
            <td><?= htmlspecialchars($dough['name']) ?></td>
            <td class="icone_e"><a href="index.php?controller=doughadmin&action=edit&id=<?= intval($dough['id']) ?>" title="modifier une pâte"><i class="fas fa-pen-nib"></i></a></td>
          </tr>
        <?php endforeach; ?>
      </tbody>
      <tfoot>
        <tr>
          <td colspan="3"><strong>($NB de pâtes au total : <?= count($doughs) ?>)</strong></td>
        </tr>
      </tfoot>
    </table>
  </div>
</div>