<p class="lien"><a href="index.php?controller=home&action=index" title="retour à l'accueil"><i class="fa fa-home"></i> Accueil /</a><a href="index.php?controller=homeadmin&action=index" title="accueil admin">Administration /</a>Liste des produits </p>
<h2><img src="assets/img/logo/signeG.svg" alt="signeG"><span> GESTION DES PRODUITS<img src="assets/img/logo/signeD.svg" alt="signeD"></span></h2>
<div class="list_product">
  <?php include 'aside_bar.phtml' ?>
  <div class=table-list>
    <?php if ($flash->hasMessages() == true) : ?>
      <div class="flash">
        <?php foreach ($flash->fetchMessages() as $message) : ?>
          <p><?= htmlspecialchars($message) ?></p>
        <?php endforeach ?>
      </div>
    <?php endif; ?>
    <h3>LISTES DES PRODUITS</h3>
    <nav class="pagination">
      <ul>
        <!-- Lien vers la page précédente (désactivé si on se trouve sur la 1ère page) -->
        <li class="page-item <?= ($currentPage == 1) ? "disabled" : "" ?>">
          <a href="index.php?controller=homeadmin&action=index&page=<?= intval($currentPage - 1) ?>" class="page-link">&lt;</a> 
        </li>
        <!-- Lien vers chacune des pages (activé si on se trouve sur la page correspondante) --> 
        <?php for ($page = 1; $page <= $pages; $page++) : ?> 
        <li class="page-item <?= ($currentPage == $page) ? "active" : "" ?>">
          <a href="index.php?controller=homeadmin&action=index&page=<?= intval($page) ?>" class="page-link"><?= intval($page) ?></a>
        </li>
        <?php endfor ?>
        <!-- Lien vers la page suivante (désactivé si on se trouve sur la dernière page) -->
        <li class="page-item <?= ($currentPage == $pages) ? "disabled" : "" ?>">
        <a href="index.php?controller=homeadmin&action=index&page=<?= intval($currentPage + 1) ?>" class="page-link">&gt;</a>
        </li>
      </ul>
    </nav>
    <table class="generic-table listproduct">
      <thead>
        <tr>
          <th>ID</th>
          <th>Image</th>
          <th>Nom du produit</th>
          <th>Type de lait</th>
          <th><a class="btn" href="index.php?controller=homeadmin&action=insert" title="insertion d'un nouveau produit"><i class="fas fa-plus"></i></a> </th>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($products as $product) : ?>
          <tr>
            <td><?= htmlspecialchars($product['id']) ?></td>
            <?php if (htmlspecialchars($product['picture']) == null) : ?>
              <td><img class="img_list" src="assets/img/no-photo.png" alt="no-photo"></td>
            <?php else : ?>
              <td><img class="img_list" src="assets/img/produit/<?= htmlspecialchars($product['picture']) ?> " alt="<?= htmlspecialchars($product['picture']) ?>"></td>
            <?php endif ?>
            <td><a href="index.php?controller=product&action=show&id=<?= intval($product['id']); ?>"><?= htmlspecialchars($product['name']) ?></a></td>
            <td><?= htmlspecialchars($product['milkName']) ?></td>
            <td class="icone_e"><a href="index.php?controller=homeadmin&action=edit&id=<?= intval($product['id']); ?>" title="modification d'un produit"><i class="fas fa-pen-nib"></i></a></td>
          </tr>
        <?php endforeach; ?>
      </tbody>
      <tfoot>
        <tr>
          <td colspan="5"><strong>($NB produits au total <?= count($products) ?>)</strong></td>
        </tr>
      </tfoot>
    </table>
  </div>
</div>
<script src="assets/js/ajax.js"></script>