<p class="lien"><a href="index.php?controller=home&action=index" title="retour à l'accueil"><i class="fa fa-home"></i> Accueil /</a><a href="index.php?controller=homeadmin&action=index" title="accueil admin">Administration /</a> Modifier un couteau </p>
<h2><img src="assets/img/logo/signeG.svg" alt="signeG"><span> GESTION DES COUTEAUX<img src="assets/img/logo/signeD.svg" alt="signeD"></span></h2>
<div class="list_product">
  <?php include 'aside_bar.phtml' ?>
  <div class=table-list>
    <a class="btn" href="index.php?controller=knifeadmin&action=insert" title="insertion d'un nouveau couteau"><i class="fas fa-plus"></i> Créer un couteau</a>
    <form method="POST" class="generic-form edit-form" enctype="multipart/form-data">
      <fieldset>
        <legend> <i class="fas fa-pen-nib"></i> Modifier un couteau</legend>
        <ul>
          <li>
            <label for="Name_knife">Nom du couteau</label>
            <input type="text" name="Name_knife" id="Name_knife" placeholder="Nom du couteau" value="<?= htmlspecialchars($knife['name']) ?>">
          </li>
          <li>
            <input type="file" name="Picture_knife">
          </li>
        </ul>
        <button class="btn" type="submit">ENREGISTRER</button>
        <a class="btn" href="index.php?controller=knifeadmin&action=index" title="retour à la liste des couteaux">RETOUR</a>
      </fieldset>      
    </form>
  </div>
</div>