<p class="lien"><a href="index.php?controller=home&action=index" title="retour à l'accueil"><i class="fa fa-home"></i> Accueil /</a><a href="index.php?controller=homeadmin&action=index" title="accueil admin">Administration /</a> Liste des couteaux </p>
<h2><img src="assets/img/logo/signeG.svg" alt="signeG"><span> GESTION DES COUTEAUX<img src="assets/img/logo/signeD.svg" alt="signeD"></span></h2>
<div class="list_product">
  <?php include 'aside_bar.phtml' ?>
  <div class=table-list>
    <?php if ($flash->hasMessages() == true) : ?>
      <aside class="flash">
        <?php foreach ($flash->fetchMessages() as $message) : ?>
          <p><?= htmlspecialchars($message) ?></p>
        <?php endforeach ?>
      </aside>
    <?php endif; ?>
    <h3>LISTES DES COUTEAUX</h3>
    <table class="generic-table listproduct">
      <thead>
        <tr>
          <th>ID</th>
          <th>Type de couteau</th>
          <th>Image</th>
          <th><a class="btn" href="index.php?controller=knifeadmin&action=insert" title="insertion d'un nouveau couteau"><i class="fas fa-plus"></i></a> </th>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($knifes as $knife) : ?>
          <tr>
            <td><?= htmlspecialchars($knife['id']) ?></td>
            <td><?= htmlspecialchars($knife['name']) ?></td>
            <?php if ($knife['picture'] == null) : ?>
              <td><img class="img_list" src="assets/img/no-photo.png" alt="no-photo"></td>
            <?php else : ?>
              <td><img class="img_list" src="assets/img/knife/<?= htmlspecialchars($knife['picture']) ?>" alt="<?= htmlspecialchars($knife['picture']) ?>"></td>
            <?php endif ?>
            <td class="icone_e"><a href="index.php?controller=knifeadmin&action=edit&id=<?= intval($knife['id']); ?>" title="modification d'un couteau"><i class="fas fa-pen-nib"></i></a></td>
          </tr>
        <?php endforeach; ?>
      </tbody>
      <tfoot>
        <tr>
          <td colspan="4"><strong>($NB de couteau au total : <?= count($knifes) ?> )</strong></td>
        </tr>
      </tfoot>
    </table>
  </div>
</div>