<p class="lien"><a href="index.php?controller=home&action=index" title="retour à l'accueil"><i class="fa fa-home"></i> Accueil /</a><a href="index.php?controller=homeadmin&action=index" title="accueil admin">Administration /</a><a href="index.php?controller=messageadmin&action=index" title="liste des messages"> Liste des messages</a> </p>
<h2><img src="assets/img/logo/signeG.svg" alt="signeG"><span> GESTION DES MESSAGES<img src="assets/img/logo/signeD.svg" alt="signeD"></span></h2>
<div class="list_product">
  <?php include 'aside_bar.phtml' ?>
  <div class=table-list>
    <h3>LISTES DES MESSAGES</h3>
    <nav class="pagination">
      <ul>
        <!-- Lien vers la page précédente (désactivé si on se trouve sur la 1ère page) -->
        <li class="page-item <?= ($currentPage == 1) ? "disabled" : "" ?>">
          <a href="index.php?controller=messageadmin&action=index&page=<?= intval($currentPage - 1) ?>" class="page-link">
            &lt;</a> </li> <?php for ($page = 1; $page <= $pages; $page++) : ?> <!-- Lien vers chacune des pages (activé si on se trouve sur la page correspondante) -->
        <li class="page-item <?= ($currentPage == $page) ? "active" : "" ?>">
          <a href="index.php?controller=messageadmin&action=index&page=<?= intval($page) ?>" class="page-link"><?= intval($page) ?></a>
        </li>
      <?php endfor ?>
      <!-- Lien vers la page suivante (désactivé si on se trouve sur la dernière page) -->
      <li class="page-item <?= ($currentPage == $pages) ? "disabled" : "" ?>">
        <a href="index.php?controller=messageadmin&action=index&page=<?= intval($currentPage + 1) ?>" class="page-link">&gt;</a>
      </li>
      </ul>
    </nav>
    <table class="generic-table listproduct">
      <thead>
        <tr>
          <th>Id</th>
          <th>Sujet</th>
          <th>Email</th>
          <th>Nom et Prénom</th>
          <th>Message</th>
          <th> </th>
          <th> </th>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($messages as $message) : ?>
          <tr>
            <td><?= htmlspecialchars($message['id']) ?></td>
            <td><?= htmlspecialchars($message['sujet']) ?></td>
            <td><?= htmlspecialchars($message['email']) ?></td>
            <td><?= htmlspecialchars($message['lastName']) ?> <?= htmlspecialchars($message['firstName']) ?></td>
            <td><?= substr($message['content'], 0,50); ?></td>
            <td><a href="index.php?controller=messageadmin&action=show&id=<?= intval($message['id']) ?>" title="edition du message"><i class="fa fa-book" aria-hidden="true"></i></a></td>
            <td class="icone_e"><a href="mailto:<?= $message['email']?>?subject=<?= str_replace(' ','',htmlspecialchars($message['sujet'])) ?>de<?= htmlspecialchars($message['lastName'])?><?= htmlspecialchars($message['firstName'])?>&body=<?=str_replace(' ','',htmlspecialchars( $message['content'])) ?>" title="redirection vers la messagerie"><i class=" fas fa-envelope"></i>
              </a></td>
          </tr>
        <?php endforeach; ?>
      </tbody>
      <tfoot>
        <tr>
         <td colspan="7"><strong>($NB de message au total <?= htmlspecialchars(count($messages)) ?>)</strong></td>
        </tr>
      </tfoot>
    </table>
  </div>
</div>