<p class="lien"><a href="index.php?controller=home&action=index" title="retour à l'accueil"><i class="fa fa-home"></i> Accueil /</a><a href="index.php?controller=homeadmin&action=index" title="accueil admin">Administration /</a> Modifier un lait </p>
<h2 class="signe"><img src="assets/img/logo/signeG.svg" alt="signeG"><span>GESTION DES LAITS<img src="assets/img/logo/signeD.svg" alt="signeD"></span></h2>
<div class="list_product">
  <?php include 'aside_bar.phtml' ?>
  <div class=table-list>
    <a class="btn" href="index.php?controller=milkadmin&action=insert" title="insertion d'un nouveau lait"><i class="fas fa-plus"></i> Créer un lait</a>
    <form  method="POST" class="generic-form edit-form">
      <fieldset>
        <legend> <i class="fas fa-pen-nib"></i> modifier le type de lait</legend>
        <ul>
          <li>
            <label for="Name_milk">Type de Lait</label>
            <input type="text" name="Name_milk" id="Name_milk" placeholder="Type de lait" value="<?= htmlspecialchars($m['name']) ?>">
          </li>
        </ul>
        <button class="btn" type="submit">ENREGISTRER</button>
        <a class="btn" href="index.php?controller=milkadmin&action=index" title="retour à la list des laits">RETOUR</a>
      </fieldset>
    </form>
  </div>  
</div>