<p class="lien"><a href="index.php?controller=home&action=index" title="retour à l'accueil"><i class="fa fa-home"></i> Accueil /</a><a href="index.php?controller=homeadmin&action=index" title="accueil admin">Administration /</a>Liste des laits </p>
<h2><img src="assets/img/logo/signeG.svg" alt="signeG"><span> GESTION DES LAITS<img src="assets/img/logo/signeD.svg" alt="signeD"></span></h2>
<div class="list_product">
  <?php include 'aside_bar.phtml' ?>
  <div class=table-list>
    <?php if ($flash->hasMessages() == true) : ?>
      <aside class="flash">
        <?php foreach ($flash->fetchMessages() as $message) : ?>
          <p><?= $message ?></p>
        <?php endforeach ?>
      </aside>
    <?php endif; ?>
    <h3>LISTES DES LAITS</h3>
    <table class="generic-table listproduct">
      <thead>
        <tr>
          <th>ID</th>
          <th>Nom du produit</th>
          <th><a class="btn" href="index.php?controller=milkadmin&action=insert" title="insertion d'un nouveau lait"><i class="fas fa-plus"></i></a> </th>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($milks as $milk) : ?>
          <tr>
            <td><?= htmlspecialchars($milk['id']) ?></td>
            <td><?= htmlspecialchars($milk['name']) ?></td>
            <td class="icone_e"><a href="index.php?controller=milkadmin&action=edit&id=<?= intval($milk['id']); ?>" title="modifier un lait"><i class="fas fa-pen-nib"></i></a></td>
          </tr>
        <?php endforeach; ?>
      </tbody>
      <tfoot>
        <tr>
          <td colspan="3"><strong>($NB laits au total : <?= count($milks) ?>)</strong></td>
        </tr>
      </tfoot>
    </table>
  </div>
</div>