<p class="lien"><a href="index.php?controller=home&action=index" title="retour à l'accueil"><i class="fa fa-home"></i> Accueil /</a><a href="index.php?controller=homeadmin&action=index" title="accueil admin">Administration /</a> Detail de la Commande </p>
<h2><img src="assets/img/logo/signeG.svg" alt="signeG"><span> GESTION DES COMMANDES<img src="assets/img/logo/signeD.svg" alt="signeD"></span></h2>
<div class="flex1 list_product showOrderline">
    <?php include 'aside_bar.phtml' ?>
    <div class=table-list>
        <h3>LISTES DES COMMANDES</h3>
        <fieldset>
            <h2>Commande Numéro <?= htmlspecialchars($_GET['id']) ?></h2>
            <table class="generic-table product-list table-order ">
                <thead>
                    <tr>
                        <th>PRODUIT</th>
                        <th>QTE</th>
                        <th>PRIX UNITAIRE</th>
                        <th>TOTAL</th>
                    </tr>
                </thead>
                <!--if panier est different de vide -->
                <tbody>
                    <?php foreach ($orderLines as $orderLine) : ?>
                        <tr>
                            <td>
                                <?php if (!empty($orderLine['Name'])) : ?>
                                    <?= htmlspecialchars($orderLine['Name']) ?>
                                <?php else : ?>
                                    <?= htmlspecialchars($orderLine['trayName']) ?>
                                <?php endif ?></td>
                            <td><?= htmlspecialchars($orderLine['quantityOrdered'])?></td>
                             <td><?= htmlspecialchars($orderLine['PriceEach']) ?> €</td>
                             <td><?= htmlspecialchars($orderLine['TotalLine']) ?> €</td>
                        </tr>
                    <?php endforeach; ?>
                    <tr class="tfoot">
                        <td>sous total</td>
                        <td></td>
                        <td></td>
                        <td><?= htmlspecialchars($orderLine['TotalAmount']) ?> €</td>
                    </tr>
                    <tr>
                        <td>Frais de port:</td>
                        <td></td>
                        <td></td>
                        <td><?= htmlspecialchars($shipping[0]['price']) ?> €</td>
                    </tr>
                    <tr class="tfoot">
                        <td>Total :</td>
                        <td></td>
                        <td></td>
                        <td><?= htmlspecialchars($orderLine['TotalAmount']) + htmlspecialchars($shipping[0]['price']) ?> €</td>
                    </tr>
                </tbody>
            </table>
            <a class="btn" href="index.php?controller=orderadmin&action=edit&id=<?=intval($_GET['id'])?>" title="retour au detail de la commande">RETOUR</a>
        </fieldset>
    </div>
</div>