<p class="lien"><a href="index.php?controller=home&action=index" title="retour à l'accueil"><i class="fa fa-home"></i> Accueil /</a><a href="index.php?controller=homeadmin&action=index" title="accueil admin">Administration /</a> Liste des commandes </p>
<h2><img src="assets/img/logo/signeG.svg" alt="signeG"><span> GESTION DES COMMANDES<img src="assets/img/logo/signeD.svg" alt="signeD"></span></h2>
<div class="flex1 list_product showOrderline">
  <?php include 'aside_bar.phtml' ?>
  <div class=table-list>
    <h3>LISTES DES COMMANDES</h3>
   <nav class="pagination">
      <ul>
        <!-- Lien vers la page précédente (désactivé si on se trouve sur la 1ère page) -->
        <li class="page-item <?= ($currentPage == 1) ? "disabled" : "" ?>">
          <a href="index.php?controller=homeadmin&action=index&page=<?= intval($currentPage - 1) ?>" class="page-link">&lt;</a> 
        </li>
        <!-- Lien vers chacune des pages (activé si on se trouve sur la page correspondante) --> 
        <?php for ($page = 1; $page <= $pages; $page++) : ?> 
        <li class="page-item <?= ($currentPage == $page) ? "active" : "" ?>">
          <a href="index.php?controller=homeadmin&action=index&page=<?= intval($page) ?>" class="page-link"><?= intval($page) ?></a>
        </li>
        <?php endfor ?>
        <!-- Lien vers la page suivante (désactivé si on se trouve sur la dernière page) -->
        <li class="page-item <?= ($currentPage == $pages) ? "disabled" : "" ?>">
        <a href="index.php?controller=homeadmin&action=index&page=<?= intval($currentPage + 1) ?>" class="page-link">&gt;</a>
        </li>
      </ul>
    </nav>
    <table class="generic-table listproduct">
      <thead>
        <tr>
          <th>NUMERO</th>
          <th>DATE</th>
          <th>STATUT</th>
          <th>TOTAL</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($orders as $order) : ?>
          <tr>
            <td><?= htmlspecialchars($order['id_order']) ?></td>
            <td><?= htmlspecialchars($order['orderDate']) ?></td>
            <td><?= htmlspecialchars($order['name']) ?></td>
            <td><?= htmlspecialchars($order['TotalAmount']) ?> €</td>
            <td class="icone_e"><a href="index.php?controller=orderadmin&action=edit&id=<?= intval($order['id_order']); ?>" title="modification d'une commande"><i class="fas fa-pen-nib"></i></a></td>
            <td><a href="index.php?controller=orderadmin&action=orderDetail&id=<?= intval($order['id_order']); ?>" title="edition d'une commande"><i class="fa fa-book" aria-hidden="true"></i></a></td>
          </tr>
        <?php endforeach; ?>
      </tbody>
      <tfoot>
        <tr>
          <td colspan="6"><strong>($NB de commande au total <?= htmlspecialchars(count($orders)) ?>)</strong></td>
        </tr>
      </tfoot>
    </table>
  </div>
</div>
