<p class="lien"><a href="index.php?controller=home&action=index" title="retour à l'accueil"><i class="fa fa-home"></i> Accueil /</a><a href="index.php?controller=homeadmin&action=index" title="accueil admin">Administration /</a>Liste des articles </p>
<h2><img src="assets/img/logo/signeG.svg" alt="signeG"><span> GESTION DES ARTICLES<img src="assets/img/logo/signeD.svg" alt="signeD"></span></h2>
<div class="list_product">
  <?php include 'aside_bar.phtml' ?>
  <div class=table-list>
    <?php if ($flash->hasMessages() == true) : ?>
      <div class="flash">
        <?php foreach ($flash->fetchMessages() as $message) : ?>
          <p><?= htmlspecialchars($message)?></p>
        <?php endforeach ?>
        </div>
    <?php endif; ?>
    <h3>LISTES DES ARTICLES</h3>
    <table class="generic-table listproduct">
      <thead>
        <tr>
          <th>Id</th>
          <th>title</th>
          <th>categorie</th>
          <th>date</th>
          <th></th>
          <th><a class="btn" href="index.php?controller=postadmin&action=insert" title="insertion d'un nouveau article"><i class="fas fa-plus"></i></a> </th>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($posts as $post) : ?>
          <tr>
            <td><?= htmlspecialchars($post['id']) ?></td>
            <td><a href="index.php?controller=blog&action=show&id=<?= intval($post['id']); ?>"><?= htmlspecialchars($post['title']) ?></a></td>
            <td><?= htmlspecialchars($post['categoryName']) ?></td>
            <td><?= htmlspecialchars($post['createdDate']) ?></td>
            <td class="icone_e"><a href="index.php?controller=postadmin&action=edit&id=<?= intval($post['id']); ?>" title="modification d'un article"><i class="fas fa-pen-nib"></i></a></td>
            <td class="icone_e"><a href="index.php?controller=postadmin&action=delete&id=<?= intval($post['id']); ?>" title="suppression d'un article" class="supprimer"><i class="fa fa-trash" aria-hidden="true"></i></a></td>
          </tr>
        <?php endforeach; ?>
      </tbody>
      <tfoot>
        <tr>
        <td colspan="6"><strong>($NB d'article au total <?= htmlspecialchars(count($posts)) ?>)</strong></td>
        </tr>
      </tfoot>
    </table>
  </div>
</div>
<script src="assets/js/ajax.js"></script>