<p class="lien"><a href="index.php?controller=home&action=index" title="retour à l'accueil"><i class="fa fa-home"></i> Accueil /</a><a href="index.php?controller=homeadmin&action=index" title="accueil admin">Administration /</a> Créer un article </p>
<h2><img src="assets/img/logo/signeG.svg" alt="signeG"><span> GESTION DES ARTICLES<img src="assets/img/logo/signeD.svg" alt="signeD"></span></h2>
<div class="list_product">
  <?php include 'aside_bar.phtml' ?>
  <div class=table-list>
    <a class="btn" href="index.php?controller=postadmin&action=insert" title="insertion d'un nouveau article"><i class="fas fa-plus"></i> Créer un produit</a>
    <form method="POST" class="generic-form edit-form" enctype="multipart/form-data">
      <fieldset>
        <legend> <i class="fas fa-pen-nib"></i> Créer un article</legend>
        <ul>
          <li>
            <label for="title_post">Titre de l'article</label>
            <input type="text" name="title_post" id="title_post" placeholder="titre de l'article" >
          </li>
          <li>
            <label for="Description_post">Description de l'article</label>
            <textarea name="Description_post" id="Description_post"></textarea>
          </li>
          <li>
            <label for="category">Catégorie</label>
            <select name="category" id="category">
              <?php foreach ($categorys as $category) : ?>
                <option value="<?= htmlspecialchars($category['id'])?>">
                  <?= htmlspecialchars($category['name']) ?>
                </option>
              <?php endforeach; ?>
            </select>
          </li>
          <li>
            <input type="file" name="Picture">
          </li>
        </ul>
        <button class="btn" type="submit">ENREGISTRER</button>
        <a class="btn" href="index.php?controller=postadmin&action=index" title="retour à la liste des articles">RETOUR</a>
      </fieldset>
    </form>
  </div>  
</div>
