<p class="lien"><a href="index.php?controller=home&action=index" title="retour à l'accueil"><i class="fa fa-home"></i> Accueil </a><a href="index.php?controller=homeadmin&action=index" title="accueil admin">Administration /</a> Créer une région </p>
<h2><img src="assets/img/logo/signeG.svg" alt="signeG"><span> GESTION DES REGIONS<img src="assets/img/logo/signeD.svg" alt="signeD"></span></h2>
<div class="list_product">
  <?php include 'aside_bar.phtml' ?>
  <div class=table-list>
    <a class="btn" href="index.php?controller=regionadmin&action=insert" title="insertion nouvelle région"><i class="fas fa-plus"></i> Créer une region</a>
    <?php if ($flash->hasMessages() == true) : ?>
      <aside class="flash">
        <?php foreach ($flash->fetchMessages() as $message) : ?>
          <p><?= htmlspecialchars($message) ?></p>
        <?php endforeach ?>
      </aside>
    <?php endif; ?>
    <form method="POST" class="generic-form edit-form" enctype="multipart/form-data">
      <fieldset>
        <legend> <i class="fas fa-pen-nib"></i> créer une nouvelle region</legend>
        <ul>
          <li>
            <label for="Name_region">Nom de la région</label>
            <input type="text" name="Name_region" id="Name_region" placeholder="Nom de la region">
          </li>
          <li>
            <input type="file" name="Picture_region">
          </li>
        </ul>
        <button class="btn" type="submit">ENREGISTRER</button>
        <a class="btn" href="index.php?controller=regionadmin&action=index" title="retour à la list des laits">RETOUR</a>
      </fieldset>
    </form>
  </div>
</div>