<p class="lien"><a href="index.php?controller=home&action=index" title="retour à l'accueil"><i class="fa fa-home"></i> Accueil /</a><a href="index.php?controller=homeadmin&action=index" title="accueil admin">Administration /</a>Modifier une région </p>
<h2><img src="assets/img/logo/signeG.svg" alt="signeG"><span> GESTION DES REGIONS<img src="assets/img/logo/signeD.svg" alt="signeD"></span></h2>
<div class="list_product">
  <?php include 'aside_bar.phtml' ?>
  <div class=table-list>
    <a class="btn" href="index.php?controller=regionadmin&action=insert" title="insertion nouvelle région"><i class="fas fa-plus"></i> Créer une region</a>
    <form  method="POST" class="generic-form edit-form" enctype="multipart/form-data">
      <fieldset>
        <legend> <i class="fas fa-pen-nib"></i> modifier une region</legend>
        <ul>
          <li>
            <label for="Name_region">Nom de la région</label>
            <input type="text" name="Name_region" id="Name_region" placeholder="Nom de la region" value="<?= htmlspecialchars($r['name'])?>">
          </li>
          <li>
            <input type="file" name="Picture_region">
          </li>
        </ul>
        <button class="btn" type="submit">ENREGISTRER</button>
      <a class="btn" href="index.php?controller=regionadmin&action=index" title="retour à la liste des régions">RETOUR</a>
      </fieldset>
    </form>
    </div>
</div>