<p class="lien"><a href="index.php?controller=home&action=index" title="retour à l'accueil"><i class="fa fa-home"></i> Accueil /</a><a href="index.php?controller=homeadmin&action=index" title="accueil admin">Administration /</a>Créer un frais de port</p>
<h2 class="signe"><img src="assets/img/logo/signeG.svg" alt="signeG"><span> GESTION DES FRAIS DE PORT <img src="assets/img/logo/signeD.svg" alt="signeD"></span></h2>
<h2><img src="assets/img/logo/signeG.svg" alt="signeG"><span> GESTION DES FRAIS DE PORT<img src="assets/img/logo/signeD.svg" alt="signeD"></span></h2>
<div class="list_product">
  <?php include 'aside_bar.phtml' ?>
  <div class=table-list>
    <a class="btn" href="index.php?controller=weightadmin&action=insert" title="insertion d'un frais de port"><i class="fas fa-plus"></i> Créer un frais port</a>
    <form method="POST" class="generic-form edit-form">
      <fieldset>
        <legend> <i class="fas fa-pen-nib"></i> Créer un frais de port</legend>
        <ul>
          <li>
            <label for="Name_shipping">Nom</label>
            <input type="text" name="Name_shipping" id="Name_shipping" placeholder="nom">
          </li>
          <li>
            <label for="Price_shipping">Prix</label>
            <input type="text" name="Price_shipping" id="Price_shipping" placeholder="prix">
          </li>
        </ul>
        <button class="btn" type="submit">ENREGISTRER</button>
        <a class="btn" href="index.php?controller=shippingadmin&action=index" title="retour à la liste des frais de port">RETOUR</a>
      </fieldset>
    </form>
  </div>
</div>