<p class="lien"><a href="index.php?controller=home&action=index" title="retour à l'accueil"><i class="fa fa-home"></i> Accueil /</a><a href="index.php?controller=homeadmin&action=index" title="accueil admin">Administration /</a> Liste des frais de port</p>
<h2><img src="assets/img/logo/signeG.svg" alt="signeG"><span> GESTION DES FRAIS DE PORT<img src="assets/img/logo/signeD.svg" alt="signeD"></span></h2>
<div class="list_product">
  <?php include 'aside_bar.phtml' ?>
  <div class=table-list>
    <?php if ($flash->hasMessages() == true) : ?>
      <aside class="flash">
        <?php foreach ($flash->fetchMessages() as $message) : ?>
          <p><?= htmlspecialchars($message) ?></p>
        <?php endforeach ?>
      </aside>
    <?php endif; ?>
    <h3>LISTES DES FRAIS DE PORT</h3>
    <table class="generic-table listproduct">
      <thead>
        <tr>
          <th>ID</th>
          <th>Nom </th>
          <th>Prix</th>
          <th><a class="btn" href="index.php?controller=shippingadmin&action=insert" title="insertion d'un frais de port"><i class="fas fa-plus"></i></a> </th>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($shippings as $shipping) : ?>
          <tr>
            <td><?= htmlspecialchars($shipping['id']) ?></td>
            <td><?= htmlspecialchars($shipping['name']) ?></td>
            <td><?= htmlspecialchars($shipping['price']) ?></td>
            <td class="icone_e"><a href="index.php?controller=shippingadmin&action=edit&id=<?= intval($shipping['id']); ?>" title="modification d'un frais de prot"><i class="fas fa-pen-nib"></i></a></td>
          </tr>
        <?php endforeach; ?>
      </tbody>
      <tfoot>
        <tr>
          <td colspan="4"><strong>($NB de poids au total : <?= count($shippings) ?>)</strong></td>
        </tr>
      </tfoot>
    </table>
  </div>
</div>