<p class="lien"><a href="index.php?controller=home&action=index" title="retour à l'accueil"><i class="fa fa-home"></i> Accueil /</a><a href="index.php?controller=homeadmin&action=index" title="accueil admin">Administration /</a>Créer un plateau </p>
<h2><img src="assets/img/logo/signeG.svg" alt="signeG"><span> GESTION DES PLATEAUX<img src="assets/img/logo/signeD.svg" alt="signeD"></span></h2>
<div class="list_product">
  <?php include 'aside_bar.phtml' ?>
  <div class=table-list>
    <a class="btn" href="index.php?controller=tray&action=insert" title="insertion d'un nouveau plateau"><i class="fas fa-plus"></i> Créer un plateau</a>
    <?php if ($flash->hasMessages() == true) : ?>
      <aside class="flash">
        <?php foreach ($flash->fetchMessages() as $message) : ?>
          <p><?= htmlspecialchars($message) ?></p>
        <?php endforeach ?>
      </aside>
    <?php endif; ?>
    <form method="POST" class="generic-form edit-form" enctype="multipart/form-data">
      <fieldset>
        <legend> <i class="fas fa-pen-nib"></i> créer un plateau</legend>
        <ul>
          <li>
            <label for="Name_tray">Nom du produit</label>
            <input type="text" name="Name_tray" id="Name_tray" placeholder="Nom du plateau">
          </li>
          <li>
            <label for="Description_tray">Description du produit</label>
            <textarea name="Description_tray" id="Description_tray" placeholder=""></textarea>
          </li>
          <li>
            <label for="Name_product1">Produit1</label>
            <select name="Name_product1" id="Name_product1">
              <option value="">--choisissez un produit--</option>
              <?php foreach ($products as $product) : ?>
                <option value="<?=  htmlspecialchars($product['id']) ?>"><?=  htmlspecialchars($product['name']) ?></option>
              <?php endforeach; ?>
            </select>
          </li>
          <li>
            <label for="Name_product2">Produit2</label>
            <select name="Name_product2" id="Name_product2">
              <option value="">--choisissez un produit--</option>
              <?php foreach ($products as $product) : ?>
                <option value="<?=  htmlspecialchars($product['id']) ?>"><?=  htmlspecialchars($product['name'])?></option>
              <?php endforeach; ?>
            </select>
          </li>
          <li>
            <label for="Name_product3">Produit3</label>
            <select name="Name_product3" id="Name_product3">
              <option value="">--choisissez un produit--</option>
              <?php foreach ($products as $product) : ?>
                <option value="<?=  htmlspecialchars($product['id']) ?>"><?=  htmlspecialchars($product['name']) ?></option>
              <?php endforeach; ?>
            </select>
          </li>
          <li>
            <label for="Name_product4">Produit4</label>
            <select name="Name_product4" id="Name_product4">
              <option value="">--choisissez un produit--</option>
              <?php foreach ($products as $product) : ?>
                <option value="<?=  htmlspecialchars($product['id']) ?>"><?=  htmlspecialchars($product['name']) ?></option>
              <?php endforeach; ?>
            </select>
          </li>
          <li>
            <label for="Name_product5">Produit5</label>
            <select name="Name_product5" id="Name_product5">
              <option value="">--choisissez un produit--</option>
              <?php foreach ($products as $product) : ?>
                <option value="<?=  htmlspecialchars($product['id']) ?>"><?=  htmlspecialchars($product['name']) ?></option>
              <?php endforeach; ?>
            </select>
          </li>
          <li>
            <label for="QuantityInStock">Quantité en stock</label>
            <input type="text" name="QuantityInStock" id="QuantityInStock" placeholder="quantité en stock">
          </li>
          <li>
            <label for="weight_tray">Poids</label>
            <select name="weight_tray" id="weight_tray">
              <option value="">--choisissez un poids--</option>
              <?php foreach ($weights as $weight) : ?>
                <option value="<?=  htmlspecialchars($weight['id']) ?>"><?=  htmlspecialchars($weight['name']) ?></option>
              <?php endforeach; ?>
            </select>
          </li>
          <li>
            <label for="BuyPrice">Prix d'achat</label>
            <input type="text" name="BuyPrice" id="BuyPrice" placeholder="prix d'achat">
          </li>
          <li>
            <label for="SalePrice">Prix de vente</label>
            <input type="text" name="SalePrice" id="SalePrice" placeholder="prix de vente">
          </li>
          <li>
            <input type="file" name="Picture">
          </li>
        </ul>
        <button class="btn" type="submit">ENREGISTRER</button>
        <a class="btn" href="index.php?controller=trayadmin&action=index" title="retour à la liste des plateaux">RETOUR</a>
      </fieldset>
    </form>
    </div>
</div>