<p class="lien"><a href="index.php?controller=home&action=index" title="retour à l'accueil"><i class="fa fa-home"></i> Accueil /</a><a href="index.php?controller=homeadmin&action=index" title="accueil admin">Administration /</a> Information d'un utilisateur </p>
<h2><img src="assets/img/logo/signeG.svg" alt="signeG"><span> GESTION DES UTILISATEURS<img src="assets/img/logo/signeD.svg" alt="signeD"></span></h2>
<div class="list_product">
  <?php include 'aside_bar.phtml' ?>
  <div class=table-list>
    <?php if ($flash->hasMessages() == true) : ?>
      <aside class="flash">
        <?php foreach ($flash->fetchMessages() as $message) : ?>
          <p><?= htmlspecialchars($message) ?></p>
        <?php endforeach ?>
      </aside>
    <?php endif; ?>
    <div class="generic-form  edit-form">
      <fieldset>
        <legend><i class="fa fa-book"></i> Identité et coordonnées</legend>
        <table id="table-form">
          <tr>
            <td>Email : </td>
            <td><?= htmlspecialchars($user['email']) ?></td>
          </tr>
          <tr>
            <td>Nom : </td>
            <td><?= htmlspecialchars($user['lastName']) ?></td>
          </tr>
          <tr>
            <td>Prénom : </td>
            <td><?= htmlspecialchars($user['firstName']) ?></td>
          </tr>
          <tr>
            <td>Date de naissance : </td>
            <td><?= htmlspecialchars($user['birthDay']) ?></td>
          </tr>
          <tr>
            <td>Adresse : </td>
            <td><?= htmlspecialchars($user['address']) ?></td>
          </tr>
          <tr>
            <td>Ville : </td>
            <td><?= htmlspecialchars($user['city']) ?></td>
          </tr>
          <tr>
            <td>Code Postal : </td>
            <td><?= htmlspecialchars($user['zipCode']) ?></td>
          </tr>
          <tr>
            <td>Pays : </td>
            <td><?= htmlspecialchars($user['country']) ?></td>
          </tr>
          <tr>
            <td>Téléphone : </td>
            <td><?= htmlspecialchars($user['phone']) ?></td>
          </tr>
        </table>
        <a class="btn" href="index.php?controller=useradmin&action=alluser" title="retour à la liste des utilisateurs">RETOUR</a>
      </fieldset>
    </div>
  </div>
</div>