<p class="lien"><a href="index.php?controller=home&action=index" title="retour à l'accueil"><i class="fa fa-home"></i> Accueil /</a><a href="index.php?controller=homeadmin&action=index" title="accueil admin">Administration /</a>Liste des utilisateurs </p>
<h2><img src="assets/img/logo/signeG.svg" alt="signeG"><span> GESTION DES UTILISATEURS<img src="assets/img/logo/signeD.svg" alt="signeD"></span></h2>
<div class="list_product">
  <?php include 'aside_bar.phtml' ?>
  <div class="table-list">
    <h3>LISTES DES UTILISATEURS</h3>
    <nav class="pagination">
      <ul>
        <!-- Lien vers la page précédente (désactivé si on se trouve sur la 1ère page) -->
        <li class="page-item <?= ($currentPage == 1) ? "disabled" : "" ?>">
          <a href="index.php?controller=useradmin&action=index&page=<?= intval($currentPage - 1) ?>" class="page-link">
            &lt;</a> </li> <?php for ($page = 1; $page <= $pages; $page++) : ?> <!-- Lien vers chacune des pages (activé si on se trouve sur la page correspondante) -->
        <li class="page-item <?= ($currentPage == $page) ? "active" : "" ?>">
          <a href="index.php?controller=useradmin&action=index&page=<?= intval($page) ?>" class="page-link"><?= intval($page) ?></a>
        </li>
      <?php endfor ?>
      <!-- Lien vers la page suivante (désactivé si on se trouve sur la dernière page) -->
      <li class="page-item <?= ($currentPage == $pages) ? "disabled" : "" ?>">
        <a href="index.php?controller=useradmin&action=index&page=<?= intval($currentPage + 1) ?>" class="page-link">&gt;</a>
      </li>
      </ul>
    </nav>
    <table class="generic-table listproduct">
      <thead>
        <tr>
          <th>Id</th>
          <th>Nom</th>
          <th>Prénom</th>
          <th>Email</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($users as $user) : ?>
          <tr>
            <td><?= htmlspecialchars($user['id']) ?></td>
            <td><?= htmlspecialchars($user['lastName']) ?></td>
            <td><?= htmlspecialchars($user['firstName']) ?></td>
            <td><?= htmlspecialchars($user['email']) ?></td>
            <td class="icone_e"><a href="index.php?controller=useradmin&action=edit&id=<?= intval($user['id']) ?>" title="voir les infos de l'utilisateur"><i class="fa fa-book"></i></a></td>
          </tr>
        <?php endforeach; ?>
      </tbody>
      <tfoot>
        <tr>
          <td colspan="5"><strong>($NB produits au total :<?= htmlspecialchars(count($users)) ?>)</strong></td>
        </tr>
      </tfoot>
    </table>
  </div>
</div>