<p class="lien"><a href="index.php?controller=home&action=index" title="retour à l'accueil"><i class="fa fa-home"></i> Accueil /</a><a href="index.php?controller=homeadmin&action=index" title="accueil admin">Administration /</a> Modifier un poids </p>
<h2><img src="assets/img/logo/signeG.svg" alt="signeG"><span> GESTION DES POIDS<img src="assets/img/logo/signeD.svg" alt="signeD"></span></h2>
<div class="list_product">
  <?php include 'aside_bar.phtml' ?>
  <div class=table-list>
    <a class="btn" href="index.php?controller=weightadmin&action=insert" title="insertion d'un nouveau poids"><i class="fas fa-plus"></i> Créer un poids</a>
    <form method="POST" class="generic-form edit-form">
      <fieldset>
        <legend> <i class="fas fa-pen-nib"></i> modifier un poids</legend>
        <ul>
          <li>
            <label for="Name_weight">poids</label>
            <input type="text" name="Name_weight" id="Name_weight" placeholder="poids" value="<?= htmlspecialchars($weight['name']) ?>">
          </li>
        </ul>
        <button class="btn" type="submit">ENREGISTRER</button>
        <a class="btn" href="index.php?controller=weightadmin&action=index" title="retour à la liste des poids">RETOUR</a>
      </fieldset>
    </form>
  </div>
</div>