<p class="lien"><a href="index.php?controller=home&action=index" title="retour à l'accueil"><i class="fa fa-home"></i> Accueil /</a><a href="index.php?controller=homeadmin&action=index" title="accueil admin">Administration /</a> Liste des poids </p>
<h2><img src="assets/img/logo/signeG.svg" alt="signeG"><span> GESTION DES POIDS<img src="assets/img/logo/signeD.svg" alt="signeD"></span></h2>
<div class="list_product">
  <?php include 'aside_bar.phtml' ?>
  <div class=table-list>
    <?php if ($flash->hasMessages() == true) : ?>
      <aside class="flash">
        <?php foreach ($flash->fetchMessages() as $message) : ?>
          <p><?= htmlspecialchars($message) ?></p>
        <?php endforeach ?>
      </aside>
    <?php endif; ?>
    <h3>LISTES DES POIDS</h3>
    <table class="generic-table listproduct">
      <thead>
        <tr>
          <th>Id</th>
          <th>Nom </th>
          <th><a class="btn" href="index.php?controller=weightadmin&action=insert" title="insertion d'un nouveau poids"><i class="fas fa-plus"></i></a> </th>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($weights as $weight) : ?>
          <tr>
            <td><?= htmlspecialchars($weight['id']) ?></td>
            <td><?= htmlspecialchars($weight['name']) ?></td>
            <td class="icone_e"><a href="index.php?controller=weightadmin&action=edit&id=<?= intval($weight['id']); ?>" title="modifier un poids"><i class="fas fa-pen-nib"></i></a></td>
          </tr>
        <?php endforeach; ?>
      </tbody>
      <tfoot>
        <tr>
        <td colspan="3"><strong>($NB de poids au total : <?= htmlspecialchars(count($weights)) ?>)</strong></td>
        </tr>
      </tfoot>
    </table>
  </div>
</div>