<p class="lien"><a href="index.php?controller=home&action=index" title="retour à l'accueil"><i class="fa fa-home"></i> Accueil </a> / A propos </p>
<article class="flex a_propos">
  <h2><img src="assets/img/logo/signeG.svg" alt="signeG"><span> NOTRE FROMAGERIE EN LIGNE<img src="assets/img/logo/signeD.svg" alt="signeD"></span></h2>
  <p>Une fromagerie en ligne qui livre.
    Des fromages exceptionnels par leur goût et leur qualité.La Fromagerie Renelle vous permet de découvrir des spécialités fromagères réservées jusqu'à ce jour aux plus grandes tables
  </p>
  <section class="presentation-img flex-js_s-a">
    <div class="flex-cc about">
      <h3>Exclusivité</h3>
      <img class=img-about src="assets/img/produit/<?= htmlspecialchars($esclusivite['picture'])?>" alt="<?= htmlspecialchars($esclusivite['picture'])?>">
    </div>
    <div class="flex-cc about">
      <h3>Spécialité</h3>
      <img class="img-about" src="assets/img/no-photo.png" alt="photo produit">
    </div>
  </section>
  <p class="element-5">Comme pour les vins,chaque région offre des variétés de fromage unique au monde.Des joyaux que nous avons sélectionnés pour leurs saveurs exceptionnelles, leur texture généreuse, leur parfums racés...avec, pour seule exigence, celle de l’excellence.</p>
  <section class="nous flex-r flex-js_s-a">
    <div class="propos">
      <h3><img src="assets/img/logo/signeG.svg" alt="signeG"> A propos de la Fromagerie RENELLE <img src="assets/img/logo/signeD.svg" alt="signeD"></h3>
      <p>Sed ut tum ad senem senex de senectute, sic hoc libro ad amicum amicissimus scripsi de amicitia. Tum est Cato locutus, quo erat nemo fere senior temporibus illis, nemo prudentior; nunc Laelius et sapiens (sic enim est habitus) et amicitiae gloria excellens de amicitia loquetur. Tu velim a me animum parumper avertas, Laelium loqui ipsum putes. C. Fannius et Q. Mucius ad socerum veniunt post mortem Africani; ab his sermo oritur, respondet Laelius, cuius tota disputatio est de amicitia, quam legens te ipse cognosces.Proinde die funestis interrogationibus praestituto imaginarius iudex equitum resedit</p>
    </div>
    <img class="img-about" src="assets/img/RenaudetEstelle.jpg" alt="photo produit">
</section>
</article>