<p class="lien"><a href="index.php?controller=home&action=index" title="retour à l'accueil"><i class="fa fa-home"></i> Accueil </a> /Conditions générales de vente</p>
<h2 class="signe"><img src="assets/img/logo/signeG.svg" alt="signeG"><span>CONDITION GENERALE DE VENTE<img src="assets/img/logo/signeD.svg" alt="signeD"></span></h2>
<div class="en_construction">
  <p>Page en construction</p>
  <div>
    <i class="fa fa-hourglass-start"></i>
  </div>
  <small>veuillez patientez...</small>
</div>