<p class="lien"><a href="index.php?controller=home&action=index" title="retour à l'accueil"><i class="fa fa-home"></i> Accueil </a>/Erreur </p>
<h2 class="signe"><img src="assets/img/logo/signeG.svg" alt="signeG"><span> AVERTISSEMENT <img src="assets/img/logo/signeD.svg" alt="signeD"></span></h2>
<a class="btn" href="index.php?controller=registration&action=index" title="retour à l'accueil">Retour à l'accueil</a>
<div class="flash">
  <p><?= $error ?></p>
</div>