<p class="lien"><a href="index.php?controller=home&action=index" title="retour à l'accueil"><i class="fa fa-home"></i> Accueil </a> / Blog</p>
<h2><img src="assets/img/logo/signeG.svg" alt="signeG"><span> A LA UNE</span><img src="assets/img/logo/signeD.svg" alt="signeD"></h2>
<div class=" comande-en-ligne">
  <?php include 'bar_blog.phtml' ?>
  <article class="clear post">
    <p><?= htmlspecialchars($post['categoryName']) ?></p>
    <?php if ($post['picture'] == null) : ?>
    <img class="img_list" src="assets/img/no-photo.png" alt="no-photo">
    <?php else : ?>
    <img class="left" src="assets/img/upload/<?= htmlspecialchars($post['picture']) ?>" alt="<?= htmlspecialchars($post['picture']) ?>" />
    <?php endif ?>
    <p><?= htmlspecialchars($post['createdDate']) ?></p>
    <h2><?= htmlspecialchars($post['title']) ?></h2>
    <p><?= htmlspecialchars($post['description']) ?></p>
    <a class="btn" href="index.php?controller=blog&action=allpost">TOUS LES ARTICLES</a>
  </article>
</div>