<p class="lien"><a href="index.php?controller=home&action=index" title="retour à l'accueil"><i class="fa fa-home"></i> Accueil /</a><a href="index.php?controller=product&action=index" title="accueil produit"> Commande à la carte</a></p>
<h2 class="signe"><img src="assets/img/logo/signeG.svg" alt="signeG"><span> COMMANDE A LA CARTE <img src="assets/img/logo/signeD.svg" alt="signeD"></span></h2>
<nav class="pagination">
  <ul>
    <!-- Lien vers la page précédente (désactivé si on se trouve sur la 1ère page) -->
    <li class="page-item <?= ($currentPage == 1) ? "disabled" : "" ?>">
      <a href="index.php?controller=product&action=index&page=<?= intval($currentPage - 1) ?>" class="page-link">
        &lt;</a> <!-- Lien vers chacune des pages (activé si on se trouve sur la page correspondante) -->
    </li> <?php for ($page = 1; $page <= $pages; $page++) : ?>
      <li class="page-item <?= ($currentPage == $page) ? "active" : "" ?>">
        <a href="index.php?controller=product&action=index&page=<?= intval($page) ?>" class="page-link"><?= $page ?></a>
      </li>
    <?php endfor ?>
    <!-- Lien vers la page suivante (désactivé si on se trouve sur la dernière page) -->
    <li class="page-item <?= ($currentPage == $pages) ? "disabled" : "" ?>">
      <a href="index.php?controller=product&action=index&page=<?= intval($currentPage + 1) ?>" class="page-link">&gt;</a>
    </li>
  </ul>
</nav>
<div class=" comande-en-ligne">
  <?php include 'bar_select.phtml' ?>
  <div class="flex-r page-produit" id="sectionarticle">
    <?php foreach ($products as $product) : ?>
      <section class="produit_Article accueil-commande" data-type="<?= htmlspecialchars($product['id_milk']) ?>">
        <form  method="post" class="basket show">
          <h3><a href="index.php?controller=product&action=show&id=<?= intval($product['id']); ?>" title="detail du produit">
              <?= htmlspecialchars($product['name']); ?></a></h3>
          <img class="" src="assets/img/produit/<?= htmlspecialchars($product['picture']); ?>" alt="<?= htmlspecialchars($product['picture']); ?>">
          <div class="prix">
            <ul>
              <li><i class="salePrice"> Prix : <?= $product['salePrice']; ?> €</i></li>
              <li><i> <?= $product['weightName']; ?></i></li>
              <li>
                <i> Qté </i>
                <input name="quantite" class="quantite" type="number" min="1" max="<?= htmlspecialchars($product['quantityInStock']) ?>" value="1" required>
                <input type="hidden" name="picture" value="assets/img/produit/<?= htmlspecialchars($product['picture']); ?>">
                <input type="hidden" name="productName" value="<?= htmlspecialchars($product['name']); ?>">
                <input type="hidden" name="productId" value="<?= htmlspecialchars($product['id']); ?>">
                <input type="hidden" name="salePrice" value="<?= htmlspecialchars($product['salePrice']); ?>">
                <input type="hidden" name="weight" value="<?= htmlspecialchars($product['weightName']); ?>">
                <input type="hidden" name="type" value="produit">
              </li>
            </ul>
          </div>
          <button class="btn button_ajout" type="submit">AJOUTER</button>
        </form>
      </section>
    <?php endforeach; ?>
  </div>
</div>
<div id="info">
  <p>Produit ajouter à votre panier</p>
  <a href="index.php?controller=product&action=index" title="accueil du produit" class="btn">POURSUIVRE</a>
  <a href="index.php?controller=basket&action=index" title="affichage du panier" class="btn">ALLER AU PANIER</a>
</div>