<p class="lien"><a href="index.php?controller=home&action=index" title="retour à l'accueil"><i class="fa fa-home"></i>Accueil</a> / Contact et plan</p>
<article>
  <h2><img src="assets/img/logo/signeG.svg" alt="signeG">CONTACT & PLAN<img src="assets/img/logo/signeD.svg" alt="signeG"></h2>
  <div class="div_contact">
    <section class="plan">
      <h3>La fromagerie Renelle</h3>
      <p>Code Postal</p>
      <p> adresse postale </p>
      <p><a href="tel:+33101010101">tel : +33101010101</a></p>
      <div class="iframe">
        <iframe src="https://maps.google.com/maps?width=100%25&amp;height=600&amp;hl=en&amp;q=orthez+(Fromagerie%20Renelle)&amp;t=&amp;z=14&amp;ie=UTF8&amp;iwloc=B&amp;output=embed"></iframe>
      </div>
    </section>
    <section class="contact2">
      <h3>CONCTACTEZ-NOUS</h3>
      <form class="generic-form form2 registration" method="POST">
        <fieldset>
          <legend><i class="fa fa-book"></i> Identité et coordonnées</legend>
          <ul>
            <li>
              <label for="sujet">Sujet:</label>
              <input id="sujet" type="text" name="sujet" value="" required>
            </li>
            <li>
              <label class="textarea" for="message">Message :</label>
              <textarea id="message" name="message" rows="3"></textarea>
            </li>
            <li>
              <label for="email">Email:</label>
              <input id="email" type="email" name="email" value="" required>
            </li>
            <li>
              <label for="lastName">Nom :</label>
              <input id="lastName" type="text" name="lastName" value="">
            </li>
            <li>
              <label for="firstName">Prénom :</label>
              <input id="firstName" type="text" name="firstName" value="">
            </li>
          </ul>
          <button class="btn" type="submit">ENVOYER</button>
        </fieldset>
      </form>
    </section>
  </div>
</article>