<?php $session = new UserSession(); ?>
<!DOCTYPE html>
<html lang="fr">
<head>
  <title>Fromagerie Renelle</title>
  <meta charset="UTF-8">
  <meta name="keywords" content="renelle,fromagerie,brebis,fromage,vache,chèvre ">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="robots" content="vente en ligne de fromage">
  <link href="https://fonts.googleapis.com/css2?family=Tangerine:wght@700&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Kaushan+Script&display=swap" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css" integrity="sha384-Bfad6CLCknfcloXFOyFnlgtENryhrpZCe29RTifKEixXQZ38WheV+i/6YWSzkz3V" crossorigin="anonymous" />
  <!-- Feuilles de styles de l'application -->
  <link rel="stylesheet" href="assets/css/normalize.css">
  <link rel="stylesheet" href="assets/css/style.css">
  <!-- Feuilles de script de l'application -->
  <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
  <script src="https://kit.fontawesome.com/b8cc345d12.js" crossorigin="anonymous"></script>
  <script src="assets/js/utilities.js"></script>
  <script src="assets/js/basket.js"></script>
  <script src="assets/js/ajax.js"></script>
  <script src="assets/js/event.js"></script>
</head>
<body>
  <!-- En-tête commune -->
  <header>
    <p id="excellence">L'EXCELLENCE EN LIGNE</p>
    <nav class="connexion">
      <!--si tu es logger -->
      <?php if ($session->isLogged()) : ?>
        <!-- et que tu es un administrateur -->
        <?php if ($session->isAdmin() == 1) : ?>
          <ul>
            <li><a href="index.php?controller=login&action=logout" title="se deconnecter"><i class="fa fa-lock" aria-hidden="true"></i>Se déconnecter</a></li>
            <li><a href="index.php?controller=homeadmin&action=index" title="accueil administration"><i class="fa fa-cog" aria-hidden="true"></i> Administration</a></li>
            <li><a class="showBasket nbr" href="index.php?controller=basket&action=index" title="mon panier"><i class="fa fa-shopping-basket" aria-hidden="true"></i> Mon panier </a></li>
            <li><a href="index.php?controller=moncompte&action=index&id=<?= $session->getIdUser() ?>" title="mon compte"><i class="fa fa-user" aria-hidden="true"></i> <?= $session->getFullName()   ?></a></li>
          </ul>
          <!-- et que tu es un un simple utilisateur -->
        <?php else : ?>
          <ul>
            <li><a href="index.php?controller=login&action=logout" title="se deconnecter"><i class="fa fa-lock" aria-hidden="true"></i>Se déconnecter</a></li>
            <li><a class="showBasket nbr" href="index.php?controller=basket&action=index"><i class="fa fa-shopping-basket" aria-hidden="true"></i>Mon panier</a></li>
            <li><a href="index.php?controller=moncompte&action=index&id=<?= $session->getIdUser() ?>" title="mon compte"><i class="fa fa-user" aria-hidden="true"></i> <?= $session->getFullName() ?></a></li>
          </ul>
        <?php endif ?>
      <?php else : ?>
        <ul>
          <li><a href="index.php?controller=login&action=index" title="mon compte"> <i class="fas fa-lock-open"></i>Se connecter</a></li>
          <li><a class="showBasket nbr" href="index.php?controller=basket&action=index" title="mon panier"><i class="fa fa-shopping-basket" aria-hidden="true"></i>Mon panier</a></li>
        </ul>
        <?php endif ?>
    </nav>
  <div class="menu-toggle">
    <i class="fas fa-bars"></i>
  </div>
  <div class="logo">
    <a href="index.php?controller=home&action=index" title="accueil"><img src="assets/img/logo/logo2.svg" alt="logo fromagerie Renelle"></a>
  </div>
  <nav class="nav-menu active">
    <ul>
      <li>
        <a href="index.php?controller=product&action=index" title="accueil des produits" id="actif">COMMANDE A LA CARTE</a>
        <div class="menu">
          <div class="sous-menu">
            <h2>Type de Laits</h2>
            <img class="img-menu" src="assets/img/produit/lait.png" alt="lait">
            <ul>
              <?php foreach ($milks as $milk) : ?>
                <li><a href="index.php?controller=product&action=GetAllByMilk&id_milk=<?= htmlspecialchars($milk['id']) ?>" title="produits par type de lait"><?= htmlspecialchars($milk['name'])?></a></li>
              <?php endforeach; ?>
            </ul>
          </div>
          <div class="sous-menu">
            <h2>Type de pâtes</h2>
            <ul>
              <?php foreach ($doughs as $dough) : ?>
                <li><a href="index.php?controller=product&action=GetAllByDough&id_dough=<?= htmlspecialchars($dough['id']) ?>" title="produits par type de pate"><?= htmlspecialchars($dough['name']) ?></a></li>
              <?php endforeach; ?>
            </ul>
          </div>
          <div class="sous-menu ">
            <h2>Régions</h2>
            <ul>
              <?php foreach ($regions as $region) : ?>
                <li><a href="index.php?controller=product&action=GetAllByRegion&id_region=<?= htmlspecialchars($region['id']) ?>" title="produits par type de region"><?= htmlspecialchars($region['name']) ?></a></li>
              <?php endforeach; ?>
            </ul>
          </div>
          <div class="sous-menu flex-c">
            <h2>L'Exclusivité du mois</h2>
            <img class="img-menu" src="assets/img/produit/<?= htmlspecialchars($esclusivite['picture']); ?>" alt="<?= htmlspecialchars($esclusivite['picture']); ?>">
            <p><?= htmlspecialchars($esclusivite['name']); ?></p>
            <p>prix : <?= htmlspecialchars($esclusivite['salePrice']); ?> </p>
            <p>poids: <?= htmlspecialchars($esclusivite['weightName']); ?> </p>
            <a class="btn" href="index.php?controller=product&action=show&id=<?= htmlspecialchars($esclusivite['id'])?>">JE DECOUVRE</a>
          </div>
        </div>
      </li>
      <li>
        <a href="index.php?controller=hometray&action=index" title="Accueil plateau">PLATEAU EVENEMENT</a>
        <div class="menu menu2">
          <div class="sous-menu sous-menu2">
            <?php foreach (array_slice($trays, 0, 3) as $tray) : ?>
              <div class="plateau-produit">
                <img class="img-menu" src="assets/img/produit/<?= htmlspecialchars($tray['picture']); ?>" alt="<?= htmlspecialchars($tray['picture']); ?>">
                <h2> <?= htmlspecialchars($tray['name']); ?> </h2>
                <a class="btn" href="index.php?controller=hometray&action=show&id=<?= htmlspecialchars($tray['id']); ?>" title="detail du plateau">JE DECOUVRE</a>
              </div>
            <?php endforeach; ?>
          </div>
        </div>
      </li>
      <li><a href="index.php?controller=about&action=index" title="page à propos">A PROPOS</a></li>
      <li><a href="index.php?controller=blog&action=index" title="accueil du blog">BLOG</a></li>
    </ul>
  </nav>
  </header>
  <main>
    <!-- Affichage du template lié à la vue -->
    <?php include_once $template ?>
  </main>
  <!-- Pied de page commun -->
  <footer class="footer">
    <div class="blog">
      <h3>Le Blog</h3>
      <ul>
        <li>
          <a href="#" title="detail article">Titre ARTICLE 1 </a>
        </li>
        <li>
          <a href="#" title="detail article">Titre ARTICLE 2 </a>
        </li>
        <li>
          <a href="#" title="detail article">Titre ARTICLE 3 </a>
        </li>
        <li>
          <a href="#" title="detail article">Titre ARTICLE 4</a>
        </li>
        <li>
          <a href="#" title="detail article">Titre ARTICLE 5</a>
        </li>
      </ul>
    </div>
    <div class="information">
      <h3>Information</h3>
      <ul>
        <li>
          <a href="index.php?controller=information&action=index" title="livraison et paiement">Livraison et paiement </a>
        </li>
        <li>
          <a href="index.php?controller=information&action=cgv" title="condition générale de vente">condition générale de vente </a>
        </li>
        <li>
          <a href="index.php?controller=information&action=mentionlegal" title="mentions légales">Mention légal</a>
        </li>
        <li>
          <a href="index.php?controller=contact&action=index" title="contact et plan">Contact et plan</a>
        </li>
      </ul>
    </div>
    <div class="contact">
      <h3>Fromagerie Renelle</h3>
      <address>
        <p> adresse postale </p>
        <p> code postale </p>
        <p><a href="mailto:fromagerieRenelle@gmail.com">fromagerieRenelle@gmail.com</a></p>
        <p><a href="tel:+33101010101">tel : +33101010101</a></p>
      </address>
      <div class="sociaux">
        <a><img src="assets/img/sociaux/square-facebook.svg" alt="logo facebook"></a>
        <a><img src="assets/img/sociaux/instagram.svg" alt="logo instagram"></a>
        <a><img src="assets/img/sociaux/pinterest.svg" alt="logo pinterest"></a>
      </div>
    </div>
    <div class="garantie">
      <h3>Nos Garanties</h3>
      <ul>
        <li>Service client à votre Ecoute</li>
        <li>Paiement sécurisé</li>
        <li>Garantie livraison fraîcheur</li>
      </ul>
    </div>
  </footer>
  
  <script src="assets/js/jquery.cookie.js"></script>
  <script src="assets/js/cookies.js"></script>
  <script src="assets/js/verif.js"></script>
  <script src="assets/js/main.js"></script>
</body>
</html>