<p class="lien"><a href="index.php?controller=home&action=index" title="retour à l'accueil"><i class="fa fa-home"></i> Accueil</a> / <a href="index.php?controller=login&action=index" title="se connecter">Se connecter</a></p>
<h2 class="signe"><img src="assets/img/logo/signeG.svg" alt="signeG"><span> <i class="fa fa-lock"></i> SE CONNECTER <img src="assets/img/logo/signeD.svg" alt="signeD"></span></h2>
<!-- Message de notification -->
<?php if ($flash->hasMessages() == true) : ?>
  <div class="flash">
    <?php foreach ($flash->fetchMessages() as $message) : ?>
      <p><?= $message ?></p>
    <?php endforeach ?>
  </div>
<?php endif; ?>
<div class="login">
  <form action="index.php?controller=login&action=cnx" method="POST" class="generic-form ">
    <fieldset>
      <legend> <i class="fas fa-lock"></i> J'ai déjà un compte </legend>
      <ul>
        <li>
          <label for="email">Email:</label>
          <input id="email" type="email" name="email" placeholder="Email" required>
        </li>
        <li>
          <label for="password">Password:</label>
          <input id="password" type="password" name="password" placeholder="Mot de passe" required>
        </li>
      </ul>
      <button class="btn" type="submit" name="login_submit">Se connecter</button>
      <a href="index.php?controller=login&action=verifmail" title="verifier que l'adresse de l'utilisateur existe" class="btn">Mot de passe oublié</a>
    </fieldset>
  </form>
  <form method="POST" class="generic-form ">
    <fieldset>
      <legend> <i class="fas fa-lock"></i> Je n'ai pas de compte </legend>
      <a href="index.php?controller=registration&action=index" title="créer un compte" class="btn" >Creer un compte</a>
    </fieldset>
  </form>
</div>