<p class="lien"><a href="index.php?controller=home&action=index" title="retour à l'accueil"><i class="fa fa-home"></i> Accueil /</a> <a href="index.php?controller=information&action=mentionlegal" title="page des mentions legals">Mention Légale</a></p>
<h2><img src="assets/img/logo/signeG.svg" alt="signeG"><span> MENTIONS LÉGALES <img src="assets/img/logo/signeD.svg" alt="signeD"></span></h2>
<section class="mentions">
  <address>
    <p>La Fromagerie Rennelle</p>
    <p>1245 Quidam malo quod verae multos qui quod </p>
    <p>00000 Orthez</p>
    <p><a href="mailto:fromagerieRenelle@gmail.com" title="redirection vers la boite mail">fromagerieRenelle@gmail.com</a></p>
    <p><a href="tel:+33000000000" title="redirection vers l'appel mobile'">(33)000000000</a></p>
  </address>
  <p>RCS :</p>
  <p>Responsable d'édition :</p>
  <p>La Fromagerie R</p>
  <p>Hébergement :</p>
  <p>__________________________</p>
  <p>__________________________</p>
  <h3>Utilisation des cookies</h3>
  <p>Utilisation des cookies sur www.lafromagerierenelle.fr :</p>
  <p>Les cookies dits « Techniques ». Ces cookies sont indispensables à la navigation sur notre site, notamment à la bonne exécution du processus de commande ;</p>
  <p>Les cookies dits « Optionnels ». Ces cookies ne sont pas indispensables à la navigation sur notre site mais peuvent permettre, par exemple, pour vous : de faciliter vos recherches, d’optimiser votre expérience d’achat, et pour nous : de mieux cibler vos attentes, d’améliorer notre offre, ou encore d’optimiser le fonctionnement de notre site.</p>
  <p>Des cookies sont également susceptibles d'être utilisés dans les espaces publicitaires de notre site.</p>
  <p> Ces espaces publicitaires vendus à des annonceurs contribuent au financement des contenus et des services que nous mettons à votre disposition.</p>
  <h3>Propriété intellectuelle et contrefaçons :</h3>
  <p>La Fromagerie Renelle est propriétaire des droits de propriété intellectuelle ou détient les droits d’usage sur les éléments accessibles sur le site : textes, images des produits, graphismes, logotype La Fromagerie Renelle, icônes. Toute exploitation non autorisée du site ou de l’un quelconque des éléments qu’il contient sera considérée comme constitutive d’une contrefaçon et poursuivie conformément aux dispositions des articles L.335-2 et suivants du Code de Propriété Intellectuelle. Toute reproduction, représentation, modification, publication, adaptation de tout ou partie des éléments du site, quel que soit le moyen ou le procédé utilisé, est interdite, sauf autorisation écrite préalable de La Fromagerie Renelle. Autres crédits photos : Page «...............</p>
</section>