<p class="lien"><a href="index.php?controller=home&action=index" title="retour à l'accueil"><i class="fa fa-home"></i>Accueil</a> / <a class="active" href="index.php?controller=moncompte&action=index&id=<?= $session->getIdUser() ?>" title="retour a la page d'accueil mon compte">Mon compte /</a> <a href="index.php?controller=moncompte&action=allorder&id=<?= $session->getIdUser() ?>" title="historique des commande">Listes des commandes /</a> Détail de la commande</p>
<h2 class="signe"><img src="assets/img/logo/signeG.svg" alt="signeG"><span> RECAPITULATIF COMMANDE<img src="assets/img/logo/signeD.svg" alt="signeD"></span></h2>
<fieldset>
    <p class="welcome">Bonjour <strong><?= $session->getFullName() ?></strong> !</p>
    <a href="index.php?controller=product&action=index" title="aller à la boutique" class="btn btn_compte">ALLER A LA BOUTIQUE</a>
    <a href="index.php?controller=moncompte&action=allorder&id=<?= $session->getIdUser() ?>" class="btn btn_compte">VOIR TOUTES LES COMMANDES</a>
    <a class="btn btn_compte" href="index.php?controller=moncompte&action=edit&id=<?= $session->getIdUser() ?>" title="vos information pesonnelles">MES INFOS PERSONNELLES</a>
    <a href="index.php?controller=moncompte&action=index&id=<?= $session->getIdUser() ?>" title="retour a mon compte" class="btn btn_compte">RETOUR</a>
    <h2>Commande Numéro <?= $_GET['id'] ?></h2>
    <table class="generic-table product-list table-order ">
        <thead>
            <tr>
                <th>Produit</th>
                <th>Quantité</th>
                <th>Prix Unitaire</th>
                <th>Total</th>
            </tr>
        </thead>
        <!--if panier est different de vide -->
        <tbody>
            <?php foreach ($orderLines as $orderLine) : ?>
                <tr>
                    <td>
                        <?php if (!empty($orderLine['Name'])) : ?>
                            <?= htmlspecialchars($orderLine['Name']) ?>
                        <?php else : ?>
                            <?= htmlspecialchars($orderLine['trayName']) ?>
                        <?php endif ?></td>
                    <td><?= htmlspecialchars($orderLine['quantityOrdered']) ?></td>
                    <td><?= htmlspecialchars($orderLine['PriceEach']) ?> €</td>
                    <td><?= htmlspecialchars($orderLine['TotalLine']) ?> €</td>
                </tr>
            <?php endforeach; ?>
            <tr class="tfoot">
                <td>sous total</td>
                <td></td>
                <td></td>
                <td><?= htmlspecialchars($orderLine['TotalAmount']) ?> €</td>
            </tr>
            <tr hidden>
                <td colspan="4" id="totalePoids"><?= htmlspecialchars($orderLines[0]['WeightTotal']) ?></td>
            </tr>
            <tr>
                <td>Frais de port:</td>
                <td></td>
                <td></td>
                <td><?= htmlspecialchars($shipping[0]['price']) ?> €</td>
            </tr>
            <tr class="tfoot">
                <td>Total :</td>
                <td></td>
                <td></td>
                <td><?= htmlspecialchars($orderLine['TotalAmount']) + htmlspecialchars($shipping[0]['price']) ?> €</td>
            </tr>
        </tbody>
    </table>
</fieldset>