<p class="lien"><a href="index.php?controller=home&action=index" title="retour à l'accueil"><i class="fa fa-home"></i>Accueil /</a> <a href="index.php?controller=basket&action=payment">Paiement de la commande</a></p>
<h2 class="signe"><img src="assets/img/logo/signeG.svg" alt="signeG"><span>MON PANIER<img src="assets/img/logo/signeD.svg" alt="signeD"></span></h2>
<nav class="nav-basket">
  <ul>
    <li><a href="index.php?controller=login&action=index" title="page de connexion"><i class="fa fa-user" aria-hidden="true"></i> Connexion</a></li>
    <li><a href="index.php?controller=basket&action=validateorder" title="validation du panier"><i class="fa fa-check" aria-hidden="true"></i> Valider </a></li>
    <li><a href="index.php?controller=basket&action=shipping" title="frais de port"><i class="fa fa-truck" aria-hidden="true"></i> Frais de port </a></li>
    <li class="active"><a href="index.php?controller=basket&action=payment" title="page paiement"><i class="fa fa-credit-card" aria-hidden="true"></i> Paiement</a></li>
  </ul>
</nav>
<div class="en_construction">
  <p>Page en construction</p>
  <div>
    <i class="fa fa-hourglass-start"></i>
  </div>
  <small>veuillez patientez...</small>
</div>