<p class="lien"><a href="index.php?controller=home&action=index" title="retour à l'accueil"><i class="fa fa-home"></i>Accueil /</a> <a href="index.php?controller=registration&action=index" title="créer un compte">Créer un compte</a></p>
<h2><img src="assets/img/logo/signeG.svg" alt="signeG"><span> INSCRIPTION <img src="assets/img/logo/signeD.svg" alt="signeD"></span></h2>
<form id="formRegistration" class="generic-form registration" action="index.php?controller=registration&action=createAccount" method="POST">
	<fieldset>
		<legend><i class="fa fa-book"></i> Identité et coordonnées</legend>
		<div id="typePass"></div>
		<ul>
			<li>
				<label for="email">Email:</label>
				<input id="email" type="email" name="email" required data-name="email">
			</li>
			<li>
				<label for="lastName">Nom :</label>
				<input id="lastName" type="text" name="lastName" required data-name="Nom">
			</li>
			<li>
				<label for="firstName">Prénom :</label>
				<input id="firstName" type="text" name="firstName" required data-name="Prénom">
			</li>
			<li>
				<label for="birthDay">Date de naissance :</label>
				<select id="birthDay" name="birthDay">
					<?php for ($day = 1; $day <= 31; $day++) : ?>
						<option value="<?= $day ?>"><?= $day ?></option>
					<?php endfor; ?>
				</select>
				<span> / </span>
				<select name="birthMonth">
					<option value="1">Janvier</option>
					<option value="2">Février</option>
					<option value="3">Mars</option>
					<option value="4">Avril</option>
					<option value="5">Mai</option>
					<option value="6">Juin</option>
					<option value="7">Juillet</option>
					<option value="8">Août</option>
					<option value="9">Septembre</option>
					<option value="10">Octobre</option>
					<option value="11">Novembre</option>
					<option value="12">Décembre</option>
				</select>
				<span> / </span>
				<select name="birthYear">
					<?php for ($year = 1940; $year <= date('Y'); $year++) : ?>
						<option value="<?= $year ?>"><?= $year ?></option>
					<?php endfor; ?>
				</select>
			</li>
			<li>
				<label class="textarea" for="address">Adresse :</label>
				<textarea id="address" name="address" rows="3"></textarea>
			</li>
			<li>
				<label for="city">Ville :</label>
				<input id="city" type="text" name="city">
			</li>
			<li>
				<label for="zipCode">Code Postal :</label>
				<input id="zipCode" class="zip-code" type="text" maxlength="5" name="zipCode" data-name="Code postal" data-type="number">
			</li>
			<li>
				<label for="country">Pays :</label>
				<input id="country" class="country" type="text" name="country">
			</li>
			<li>
				<label for="phone">Téléphone :</label>
				<input id="phone" class="phone" type="text" maxlength="10" name="phone" data-name="Téléphone" data-type="number">
			</li>
			<li>
				<label for="password">Mot de passe :</label>
				<input type="password" id="password" name="password">
			</li>
		</ul>
		<button id="registration" class="btn" type="submit" value="Créer le compte" name="registration_submit">Créer le compte</button>
	</fieldset>
</form>
<script src="assets/js/verif.js"></script>