<p class="lien"><a href="index.php?controller=home&action=index" title="retour à l'accueil"><i class="fa fa-home"></i> Accueil /</a><a href="index.php?controller=blog&action=index" title="accueil du blog">Blog /</a><?= $post['title'] ?> </p>
<h2><img src="assets/img/logo/signeG.svg" alt="signeG"><span> <?= htmlspecialchars($post['title'])?> </span><img src="assets/img/logo/signeD.svg" alt="signeD"></h2>
<div class=" comande-en-ligne">
  <?php include 'bar_blog.phtml' ?>
  <section class="clear post">
    <p><?= htmlspecialchars($post['categoryName']) ?></p>
    <img class="left" src="assets/img/upload/<?= htmlspecialchars($post['picture']) ?>" alt="<?= htmlspecialchars($post['picture']) ?>" />
    <p><?= htmlspecialchars($post['createdDate'])?></p>
    <h2><?= htmlspecialchars($post['title']) ?></h2>
    <p> <?= htmlspecialchars($post['description']) ?></p>
    <a class="btn" href="index.php?controller=blog&action=allpost">TOUS LES ARTICLES</a>
  </section>
</div>
