<p class="lien"><a href="index.php?controller=home&action=index" title="retour à l'accueil"><i class="fa fa-home"></i>Accueil</a> /Validation commande</p>
<h2 class="signe"><img src="assets/img/logo/signeG.svg" alt="signeG"><span>MON PANIER<img src="assets/img/logo/signeD.svg" alt="signeD"></span></h2>
<nav class="nav-basket">
  <ul>
    <li><a href="index.php?controller=login&action=index" title="page de connexion"><i class="fa fa-user" aria-hidden="true"></i> Connexion</a></li>
    <li class="active"><a href="index.php?controller=basket&action=validateorder" title="validation du panier"><i class="fa fa-check" aria-hidden="true"></i> Valider </a></li>
    <li><a href="index.php?controller=basket&action=shipping" title="frais de port"><i class="fa fa-truck" aria-hidden="true"></i> Frais de port</a></li>
    <li><a><i class="fa fa-credit-card" aria-hidden="true" title="page paiement"></i> Paiement</a></li>
  </ul>
</nav>
<form method="post" class="form-basket generic-form">
  <h3>Récapitulatif du Panier</h3>
  <div class="fact_liv">
    <fieldset class="facturation">
      <legend>Adresse de Facturation</legend>
      <div class="edit-form">
        <p><?= htmlspecialchars($user['lastName']) ?></p>
        <p><?= htmlspecialchars($user['firstName']) ?></p>
        <p><?= htmlspecialchars($user['address']) ?></p>
        <p><?= htmlspecialchars($user['zipCode']) ?></p>
        <p><?= htmlspecialchars($user['city']) ?></p>
        <p><?= htmlspecialchars($user['phone']) ?></p>
      </div>
    </fieldset>
    <fieldset class="livraison">
      <legend>Adresse de Livraison</legend>
      <div class="edit-form">
        <p><?= htmlspecialchars($user['lastName']) ?></p>
        <p><?= htmlspecialchars($user['firstName']) ?></p>
        <p><?= htmlspecialchars($user['address']) ?></p>
        <p><?= htmlspecialchars($user['zipCode']) ?></p>
        <p><?= htmlspecialchars($user['city']) ?></p>
        <p><?= htmlspecialchars($user['phone']) ?></p>
      </div>
    </fieldset>
  </div>
  <table class="generic-table product-list" id="list">
    <thead>
      <tr>
        <th>PRODUIT</th>
        <th></th>
        <th class="number">prix</th>
        <th class="number">Quantité </th>
        <th class="number">Total</th>
        <th class="number"></th>
      </tr>
    </thead>
    <tbody id="panier1">
    </tbody>
    <tfoot>
      <tr class="tfoot">
        <td colspan="4">Total panier :</td>
        <td class="number" colspan="1" id="totale">€</td>
        <td></td>
      </tr>
      <tr hidden>
        <td colspan="5" id="totalePoids"></td>
        <td></td>
      </tr>
    </tfoot>
  </table>
  <a href="index.php?controller=product&action=index" title="retour a l'accueil produit" class="btn">RETOUR A LA BOUTIQUE</a>
  <button id="validationcommande" class="btn" type="submit">VALIDER LA COMMANDE</button>
</form>
<script src="assets/js/validate.js"></script>