<p class="lien"><a href="index.php?controller=home&action=index" title="retour à l'accueil"><i class="fa fa-home"></i> Accueil</a> / <a href="index.php?controller=login&action=index" title="se connecter">Se connecter</a></p>
<h2 class="signe"><img src="assets/img/logo/signeG.svg" alt="signeG"><span> <i class="fa fa-lock"></i> MOT DE PASSE OUBLIE <img src="assets/img/logo/signeD.svg" alt="signeD"></span></h2>
<?php if ($flash->hasMessages() == true) : ?>
  <div class="flash">
    <?php foreach ($flash->fetchMessages() as $message) : ?>
      <p><?= $message ?></p>
    <?php endforeach ?>
    </div>
<?php endif; ?>
<form  method="POST" class="generic-form verif ">
  <fieldset>
    <legend> <i class="fas fa-lock"></i> Vérification de votre email</legend>
    <ul>
      <li>
        <label for="email">Email:</label>
        <input id="email" type="email" name="email" placeholder="Email" required>
      </li>
    </ul>
  </fieldset>
  <button class="btn" type="submit" name="continuer">continuer</button>
  <a href="index.php?controller=login&action=index" title="retour a la page de connexion" class="btn">RETOUR </a>
</form>